services:
  app:
    platform: linux/amd64
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV:-production} # 从命令行参数中读取，默认值为 production
        SERVICE_PORT: ${SERVICE_PORT:-9000} # 从环境变量中读取，默认值为 9000
    image: ${IMAGE_NAME} # 使用外部传递的镜像名称  # 动态设置镜像名称
    ports:
      - '${SERVICE_PORT:-9000}:${SERVICE_PORT:-9000}' # 设置默认值为 9000
    environment:
      NODE_ENV: ${NODE_ENV:-production} # 从外部环境变量中读取，默认值为 production
      RABBITMQ_HOST: rabbitmq # RabbitMQ主机地址
      RABBITMQ_PORT: 5672 # RabbitMQ端口
      RABBITMQ_USERNAME: guest # RabbitMQ用户名
      RABBITMQ_PASSWORD: guest # RabbitMQ密码
    depends_on:
      - rabbitmq # 依赖RabbitMQ服务
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672' # AMQP协议端口
      - '15672:15672' # 管理界面端口
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - app-network

volumes:
  rabbitmq_data:
  rabbitmq_logs:

networks:
  app-network:
    driver: bridge
